url: https://dandelinaturevisit.in
plugins:
  - jekyll-sitemap
baseurl: /

# Site settings
title: Dandeli Nature Visit
email: your-email@domain.com
description: "The opportunity to get up-close to nature is possible here and nowhere else, thick evergreen forests, rivers, gushing waterfalls, chirping birds, greenery everywhere make your heart fill with joy."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/100464705426226/posts/102900121849351/?substory_index=0&flite=scwspnss

# Postal address (add as many lines as necessary)
address:
  - line: Dandeli, KA 581325

# Build settings
markdown: kramdown
permalink: pretty